# Generated by Django 5.2.7 on 2025-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'ثبت شده'), ('CONFIRMED', 'تایید شده'), ('PREPARING', 'در حال آماده\u200cسازی'), ('DELIVERED', 'تحویل داده شده'), ('CANCELED', 'لغو شده')], default='PLACED', max_length=50),
        ),
    ]
