# Generated by Django 5.2.7 on 2025-10-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'شرکت\u200cها'},
        ),
    ]
