# Generated by Django 5.2.7 on 2025-10-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'دسته\u200cبندی\u200cهای غذا'},
        ),
    ]
