# Generated by Django 5.2.7 on 2025-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount of the transaction. Positive or negative values allowed.', max_digits=10),
        ),
    ]
